In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
pd.set_option('display.max_columns', None)

In [2]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [3]:
Target = pd.read_csv("target.csv")
Numerical = pd.read_csv("numerical.csv")
Categorical = pd.read_csv("categorical.csv")

In [4]:
#we encode categoricals
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first').fit(Categorical)
encoded_categorical = encoder.transform(Categorical).toarray()
encoded_categorical = pd.DataFrame(encoded_categorical)

In [5]:
df = pd.concat([Numerical, encoded_categorical, Target], axis=1)

In [6]:
y=df['TARGET_B']
X=df.drop(columns=['TARGET_B'])

In [7]:
from sklearn.tree import DecisionTreeRegressor
model1 = DecisionTreeRegressor()
from sklearn.linear_model import LinearRegression
model2 = LinearRegression()
from sklearn.neighbors import KNeighborsRegressor
model3 = KNeighborsRegressor()
from sklearn.preprocessing import StandardScaler
import numpy as np

In [8]:
scaler= StandardScaler()
X=scaler.fit_transform(df)

/Users/matiasgroblunecke/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/Users/matiasgroblunecke/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [9]:
#define models
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25)

In [10]:
#split train and test
from sklearn.model_selection import cross_val_score

model_pipeline = [model1, model2, model3]
model_names = ['Decision Tree Regressor', 'Linear Regression', 'KNN']
model = DecisionTreeRegressor()

In [11]:
scores = cross_val_score(model, X, y, cv=5) 
scores

array([1., 1., 1., 1., 1.])

In [12]:
scores = {}
for model, model_name in zip(model_pipeline, model_names):
    mean_score = np.mean(cross_val_score(model, X_train, y_train, cv=10))
    scores[model_name] = mean_score
print(scores)

{'Decision Tree Regressor': 1.0, 'Linear Regression': 0.4941358322414821, 'KNN': 0.0931804585949332}


In [13]:
list(zip(model_pipeline, model_names))

[(DecisionTreeRegressor(), 'Decision Tree Regressor'),
 (LinearRegression(), 'Linear Regression'),
 (KNeighborsRegressor(), 'KNN')]

In [14]:
val_scores = {}

for model, model_name in zip(model_pipeline,model_names):
    model.fit(X_train, y_train)
    val_scores[model_name] = model.score(X_val,y_val)
print(val_scores)

{'Decision Tree Regressor': 1.0, 'Linear Regression': 0.8506873786745246, 'KNN': 0.08056052960254934}


In [15]:
transformer = StandardScaler().fit(X)
X = transformer.transform(X)

In [16]:
regr = DecisionTreeRegressor(max_depth=10,
                             criterion = 'squared_error',
                             min_samples_split=2,
                             min_samples_leaf = 1,
                             max_features = 6)


In [18]:
from sklearn.model_selection import cross_validate

results = cross_validate(regr,X_train, y_train, cv = 5)

In [19]:
print(results['test_score'])

[ 0.0152471   0.57317815  0.01416952 -0.03560862 -0.01805747]


In [20]:
print(results['test_score'].mean())

0.10978573556789115


In [21]:
model_pipeline = [model1, model2, model3]
model_names = ['Decision Tree Regressor', 'Linear Regression', 'KNN']

In [22]:
scores = {}
for model, model_name in zip(model_pipeline, model_names):
    mean_score = np.mean(cross_val_score(model, X_train, y_train, cv=10))
    scores[model_name] = mean_score
print(scores)

{'Decision Tree Regressor': 1.0, 'Linear Regression': 0.4941358322414821, 'KNN': 0.0931804585949332}


In [25]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [26]:
y=df['TARGET_B']
X=df.drop(columns=['TARGET_B'])

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [28]:
X_train.shape

(76329, 635)

In [29]:
y_train.shape

(76329,)

In [30]:
trainset = pd.concat([X_train, y_train], axis=1)

In [31]:
category_0 = trainset[trainset['TARGET_B']==0].sample(len(trainset[trainset['TARGET_B']==1]))
print(category_0.shape)

(3843, 636)


In [32]:
category_1 = trainset[trainset['TARGET_B']== 1 ]

In [33]:
trainset_new = pd.concat([category_0, category_1], axis = 0)
trainset_new = trainset_new.sample(frac =1)

In [34]:
X_train = trainset_new.drop(['TARGET_B'], axis=1)
y_train = trainset_new['TARGET_B']
print(X_train.shape)

(7686, 635)


In [35]:
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)
y_train_regression = X_train['TARGET_D']
y_test_regression = X_test['TARGET_D']

In [36]:
X_train = X_train.drop(['TARGET_D'], axis = 1)
X_test = X_test.drop(['TARGET_D'], axis = 1)

In [37]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

clf = RandomForestClassifier(max_depth=5, # max number of questions to ask.
                             min_samples_split=20, # amnount of rows still considered at every question
                             min_samples_leaf =20, # ultimate answer based on at least this many rows.
                             max_samples=0.8, #fraction of X-train to use in each tree
                             random_state = 42)

In [38]:
clf.fit(X_train, y_train)
print(clf.score(X_train, y_train))
print(clf.score(X_test, y_test))

0.6403851157949518
0.5554158151234083


In [39]:
y_pred = clf.predict(X_test)
display(y_test.value_counts())

0    18083
1     1000
Name: TARGET_B, dtype: int64

In [40]:
display(confusion_matrix(y_test, y_pred))

array([[10021,  8062],
       [  422,   578]])

In [41]:
from sklearn.model_selection import cross_val_score
clf = RandomForestClassifier(max_depth=5,
                             min_samples_split=20,
                             min_samples_leaf =20)
cross_val_scores = cross_val_score(clf, X_train, y_train, cv=10)
print(np.mean(cross_val_scores))

0.577541009698743


In [42]:
cross_val_scores

array([0.5786736 , 0.56306892, 0.57997399, 0.59557867, 0.56306892,
       0.6046814 , 0.59505208, 0.58203125, 0.56770833, 0.54557292])

In [43]:
cross_val_score(clf, X_train,y_train,cv=5, scoring='recall_macro')

array([0.57737321, 0.58488432, 0.5744685 , 0.58296083, 0.55953602])